const FreeTimeQuestions = {
	locale: "es",
	title: "¿A qué dedicas tu tiempo libre?",
	logoPosition: "right",
	pages: [
		{
			name: "Deportes y Entrenamientos",
			elements: [
				{
					type: "checkbox",
					name: "Practicar Deportes",
					title: "¿Practicas algún deporte? ",
					isRequired: true,
					choices: [
						"Fútbol",
						"Baloncesto",
						"Béisbol",
						"Artes Marciales",
						"Natación",
						"Tenis",
					],
					hasOther: true,
					hasNone: true,
					noneText: "Ninguno",
					otherText: "¿Otro? ¿Cuál?",
					colCount: 3,
					hasSelectAll: true,
					selectAllText: "Todos",
				},
				{
					type: "checkbox",
					name: "Entrenar",
					title: "¿Cuáles entrenamientos realizas?",
					isRequired: true,
					choices: [
						"Gimnacio",
						"Yoga",
						"Spinnig",
						"Jogging o Running",
						"Crossfit",
						"Pilates",
					],
					hasOther: true,
					hasNone: true,
					noneText: "Ninguno",
					otherText: "¿Otro? ¿Cuál?",
					colCount: 3,
					hasSelectAll: true,
					selectAllText: "Todos",
				},
			],
			title: {
				default: "¿A qué dedicas tu tiempo libre?",
				es: "Deportes y Entrenamientos\n",
			},
			description: {
				default: "Deportes y Entrenamientos",
				es: "\n",
			},
		},
		{
			name: "Géneros y Tipos de Programas",
			elements: [
				{
					type: "checkbox",
					name: "Ver TV",
					title: "¿Qué tipo de contenido prefieres?",
					isRequired: true,
					choices: [
						"Películas",
						"Series",
						"Telenovelas",
						"Documentales",
						"Anime",
						"Doramas",
						"Shows",
					],
					hasNone: true,
					noneText: "Ninguno",
					colCount: 3,
					hasSelectAll: true,
					selectAllText: "Todos",
				},
				{
					type: "checkbox",
					name: "Géneros TV",
					title: "¿Cuáles géneros te gustan? ",
					isRequired: true,
					choices: [
						"Comedia",
						"Drama",
						"Terror",
						"Aventura",
						"Ciencia Ficción",
						"Acción",
						"Biografía",
						"Musical",
						"Policíaco",
						"Animados",
					],
					hasNone: true,
					noneText: "Ninguno",
					colCount: 3,
					hasSelectAll: true,
					selectAllText: "Todos",
				},
				{
					type: "checkbox",
					name: "Programas TV",
					title: "¿Qué tipo de programas prefieres? ",
					isRequired: true,
					choices: [
						"Cocina",
						"Supervivencia",
						"Entrevistas a celebridades",
						"Concursos",
						"Reality",
						"Noticieros",
						"Humorísticos",
					],
					hasNone: true,
					noneText: "Ninguno",
					colCount: 3,
					hasSelectAll: true,
					selectAllText: "Todos",
				},
			],
			title: {
				default: "¿A qué dedicas tu tiempo libre? ",
				es: "Géneros y Tipos de Programas",
			},
			description: {
				default: "Géneros y Tipos de Programas",
				es: "\n",
			},
		},
		{
			name: "Sagas",
			elements: [
				{
					type: "checkbox",
					name: "Sagas Favoritas",
					title: "¿Cuáles son tus sagas preferidas? ",
					isRequired: true,
					choices: [
						"Harry Potter",
						"El Señor de los Anillos",
						"The Hobbit",
						"Star Wars",
						"The Matrix",
						"X-Men",
						"The Hunger Games",
						"Universo Marvel",
						"Universo DC",
						"Piratas del Caribe",
						"El Padrino",
						"Rocky",
						"007",
						"Star Trek",
						"Indiana Jones",
						"Terminator",
						"Jurassic Park",
						"The Fast & The Furious",
						"Saw",
					],
					hasOther: true,
					hasNone: true,
					noneText: "Ninguno",
					otherText: "¿Otro? ¿Cuál?",
					colCount: 4,
					hasSelectAll: true,
					selectAllText: "Todos",
				},
				{
					type: "checkbox",
					name: "Películas Favoritas",
					title: "¿Cuáles son tus pelis favoritas? ",
					isRequired: true,
					choices: [
						"Forrest Gump",
						"Casablanca",
						"Intocable",
						"The Departed",
						"Titanic",
						"Gladiator",
						"El pianista",
						"Léon: The Professional",
						"Dirty Dancing",
						"Parasite",
						"The Green Mile",
						"Saving Private Ryan",
						"La vida es bella",
						"El silencio de los corderos",
						"Figth Club",
						"Pulp Fiction",
						"La lista de Schindler",
						"Cadena Perpetua",
						"Scarface",
						"Braveheart",
						"Bohemian Rhapsody",
						"Django Unchained",
						"El resplandor",
						"Inception",
						"The Imitation Game",
						"Inglourious Basterds",
					],
					hasOther: true,
					hasNone: true,
					noneText: "Ninguno",
					otherText: "¿Otro? ¿Cuál?",
					colCount: 4,
					hasSelectAll: true,
					selectAllText: "Todos",
				},
				{
					type: "checkbox",
					name: "Animados Favoritos",
					title: "¿Cuáles muñes adoras? ",
					isRequired: true,
					choices: [
						"La Era del Hielo",
						"Shrek",
						"Toy Story",
						"Up",
						"Coco",
						"Wall-E",
						"Brave",
						"Frozen",
						"Soul",
						"El viaje de Chihiro",
						"La tumba de las luciérnagas",
						"La Princesa Mononoke",
						"El Rey León",
						"Mulán",
						"Despicable Me",
						"Kung-Fu Panda",
						"Madagascar",
						"Los Increíbles",
						"Ratatouille",
						"Monster INC",
						"Finding Nemo",
						"El castillo ambulante",
					],
					hasOther: true,
					hasNone: true,
					noneText: "Ninguno",
					otherText: "¿Otro? ¿Cuál?",
					colCount: 4,
					hasSelectAll: true,
					selectAllText: "Todos",
				},
				{
					type: "checkbox",
					name: "Series Favoritas",
					title: "¿Cuáles series prefieres? ",
					isRequired: true,
					choices: [
						"Game of Thrones",
						"Peaky Blinders",
						"Vikings",
						"La Casa de Papel",
						"Friends",
						"The Big Bang Theory",
						"How I Met Your Mother",
						"Aída",
						"La que se avecina",
						"Aquí no hay quien viva",
						"The Witcher",
						"Entourage",
						"The Handmaid's Tale",
						"Futurama",
						"The Simpsons",
						"Silicon Valley",
						"Big Little Lies",
						"Spartacus",
						"Sons of Anarchy",
						"Mr. Robot",
						"Adventure Time",
						"The Crown",
						"Westworld",
						"BoJack Horseman",
						"South Park",
						"House of Cards",
						"Stranger Things",
						"Dark",
						"The Mandalorian",
						"Gravity Falls",
						"The Sopranos",
						"Rick and Morty",
						"Avatar: The Last Airbender",
						"Breaking Bad",
						"The Walking Dead",
						"Euphoria",
						"Squid Game",
						"You",
						"Sex Education",
						"The Umbrella Academy",
						"Arcane",
					],
					hasOther: true,
					hasNone: true,
					noneText: "Ninguno",
					otherText: "¿Otro? ¿Cuál?",
					colCount: 5,
					hasSelectAll: true,
					selectAllText: "Todos",
				},
				{
					type: "checkbox",
					name: "Animes Favoritos",
					title: "¿Cuáles animes te gustan? ",
					isRequired: true,
					choices: [
						"Shingeki no Kyojin",
						"Naruto",
						"One Piece",
						"Bleach",
						"Voltes V",
						"Kimetsu no Yaiba",
						"Fullmetal Alchemist",
						"Dragon Ball Z",
						"Death Note",
						"Sailor Moon",
						"Hunter X Hunter",
						"My Hero Academia",
						"Jujutsu Kaisen",
						"Cowboy Bebop",
						"Fairy Tail",
						"Dead Man Wonderland",
						"Boruto",
						"Berserk",
						"Black Clover",
						"Tensei Shitara Slime Datta Ken",
						"Vinland Saga",
						"Mushoku Tensei",
					],
					hasOther: true,
					hasNone: true,
					noneText: "Ninguno",
					otherText: "¿Otro? ¿Cuál?",
					colCount: 4,
					hasSelectAll: true,
					selectAllText: "Todos",
				},
			],
			title: {
				default: "¿A qué dedicas tu tiempo libre? ",
				es: "Tus Favoritos",
			},
			description: {
				default: "Tus Favoritos",
				es: "\n",
			},
		},
		{
			name: "videogames",
			elements: [
				{
					type: "checkbox",
					name: "Géneros Videojuegos",
					title: "¿Qué tipos de videojuegos te gustan?",
					isRequired: true,
					choices: [
						"Arcade",
						"Plataformas",
						"Disparos",
						"Peleas",
						"Aventura de Acción",
						"Aventura Gráfica",
						"Juegos de Rol (RPG)",
						"Puzzle",
						"Didáctido",
						"Estrategia",
						"Simulación",
						"Carreras",
						"Deportes",
						"Juegos de Mesa",
					],
					hasNone: true,
					noneText: "Ninguno",
					colCount: 3,
					hasSelectAll: true,
					selectAllText: "Todos",
				},
				{
					type: "checkbox",
					name: "Videojuegos Favoritos",
					title: "¿Cuáles son tus videojuegos favoritos? ",
					isRequired: true,
					choices: [
						"Fifa",
						"Call of Duty",
						"Dota",
						"Axie Infinity",
						"The Legend of Zelda",
						"Red Dead Redemption",
						"Persona 5 Royal",
						"Super Smash Bros",
						"Super Mario",
						"The Last of Us",
						"Forza Horizon",
						"Grand Theft Auto",
						"God of War",
						"Fortnite",
						"StarCraft",
						"The Elder Scrolls V: Skyrim",
						"Sekiro: Shadows Die Twice",
						"BioShock",
						"Uncharted",
						"The Witcher",
						"Bloodborne",
						"Divinity",
						"Minecraft",
						"Doom",
						"Just Dance",
						"Dark Souls",
						"Final Fantasy",
						"Pokémon",
						"Dragon Quest",
						"Fallout",
						"Crysis",
						"Mario Kart",
						"Monster Hunter",
						"Warcraft",
						"Far Cry",
						"Batman",
						"League of Legends",
						"Rust",
						"VALORANT",
						"Garena Free Fire",
						"Counter-Strike: Global Offensive",
						"Assassin's Creed",
						"Clash Royale",
						"Among Us",
						"PlayerUnknown's Battlegrounds",
						"Cyberpunk 2077",
						"Battlefield",
						"Halo",
					],
					hasOther: true,
					hasNone: true,
					noneText: "Ninguno",
					otherText: "¿Otro? ¿Cuál?",
					colCount: 5,
					hasSelectAll: true,
					selectAllText: "Todos",
				},
			],
			title: {
				default: "¿A qué dedicas tu tiempo libre? ",
				es: "Videojuegos",
			},
			description: {
				default: "Videojuegos",
				es: "\n",
			},
		},
		{
			name: "Música",
			elements: [
				{
					type: "checkbox",
					name: "Géneros Musicales",
					title: "¿Cuáles géneros musicales prefieres? ",
					isRequired: true,
					choices: [
						"Clásica",
						"Blues",
						"Jazz",
						"Rock and Roll",
						"Soul",
						"Rock",
						"Metal",
						"Country",
						"Disco",
						"Electrónica",
						"Pop",
						"Reggae",
						"Salsa",
						"Hip Hop",
						"Reggaeton",
						"Trova",
					],
					hasNone: true,
					noneText: "Ninguno",
					colCount: 3,
					hasSelectAll: true,
					selectAllText: "Todos",
				},
				{
					type: "checkbox",
					name: "Artistas Favoritos",
					title: "¿Cuáles artistas sueles escuchar? ",
					isRequired: true,
					choices: [
						"The Weeknd",
						"Justin Bieber",
						"Ed Sheeran",
						"Dua Lipa",
						"Adele",
						"Coldplay",
						"Imagine Dragons",
						"Ariana Grande",
						"Bruno Mars",
						"Drake",
						"Taylor Swift",
						"J Balvin",
						"Elton John",
						"David Guetta",
						"Billie Eilish",
						"Eminem",
						"Post Malone",
						"Rihanna",
						"BTS",
						"Bad Bunny",
						"Queen",
						"Shawn Mendes",
						"Maroon 5",
						"Elvis Presley",
						"Bob Marley",
						"The Beatles",
						"Michael Jackson",
						"Prince",
						"Whitney Houston",
						"Christina Aguilera",
						"Nirvana",
						"The Rolling Stones",
						"U2",
						"Pink Floyd",
						"Led Zeppelin",
						"Metallica",
						"Guns N Roses",
						"AC/DC",
						"Spice Girls",
						"Backstreet Boys",
						"OneRepublic",
						"Avicii",
						"Los Aldeanos",
						"Gente de Zona",
						"Buena Fe",
						"Leoni Torres",
						"Silvio Rodríguez",
						"Pablo Milanés",
						"Calle 13",
						"Ozuna",
						"Maluma",
						"Cimafunk",
						"Decemer Bueno",
						"Ricardo Arjona",
						"Marc Anthony",
						"Nicky Jam",
						"Anuel AA",
						"Karol G",
						"Alejandro Sanz",
						"Shakira",
						"Beyonce",
						"Lady Gaga",
						"Kelvis Ochoa",
						"X Alfonso",
						"Carlos Varela",
						"Frank Delgado",
						"Los Van Van",
					],
					hasOther: true,
					hasNone: true,
					noneText: "Ninguno",
					otherText: "¿Otro? ¿Cuál?",
					colCount: 5,
					hasSelectAll: true,
					selectAllText: "Todos",
				},
			],
			title: {
				default: "¿A qué dedicas tu tiempo libre? ",
				es: "Música\n",
			},
			description: {
				default: "Música",
				es: "\n",
			},
		},
		{
			name: "Literatura",
			elements: [
				{
					type: "checkbox",
					name: "Literatura Favorita",
					title: "¿Qué tipo de literatura disfrutas leer? ",
					isRequired: true,
					choices: [
						"Ficción",
						"Fantasía",
						"Poesía",
						"No Ficción",
						"Romántica",
						"Historietas",
						"Érotica",
						"Policíaca",
						"Misterio",
						"Terror",
						"Científica",
						"Autoayuda",
						"Cocina",
						"Filosófica",
					],
					hasNone: true,
					noneText: "Ninguno",
					colCount: 2,
					hasSelectAll: true,
					selectAllText: "Todos",
				},
				{
					type: "checkbox",
					name: "Autores Favoritos",
					title: "¿Cuáles son tus autores preferidos?  ",
					isRequired: true,
					choices: [
						"Miguel de Cervantes",
						"William Shakespeare",
						"Jorge Luis Borges",
						"Franz Kafka",
						"Dante",
						"Marqués de Sade",
						"Lope de Vega",
						"Albert Camus",
						"Pablo Neruda",
						"Mario Benedetti",
						"Rubén Darío",
						"Federico García Lorca",
						"Gabriela Mistral",
						"Isable Allende",
						"Gabriel García Márquez",
						"José Martí",
						"Oscar Wilde",
						"Fiódor Dostoyevski",
						"Stephen King",
						"Julio Verne",
						"Ernest Hemingway",
						"J.K. Rowling",
						"Agatha Christie",
						"J. R. R. Tolkien",
						"Eduardo Galeano",
						"William Faulkner",
						"James Joyce",
						"George Orwell",
						"Haruki Murakami",
						"Charles Dickens",
						"Charles Darwin",
						"Herman Melville",
						"Arthur Conan Doyle",
						"Edgar Allan Poe",
						"Lewis Carroll",
						"Robert Louis Stevenson",
						"Nicolás Maquiavelo",
						"Hermann Hesse",
						"Jack London",
						"Alejo Carpentier",
						"José María Heredia",
						"Cirilo Villaverde",
						"Gertrudis Gómez de Avellaneda",
						"Julián del Casal",
						"Dulce María Loynaz",
						"Nicolás Guillén",
						"José Lezama Lima",
						"Virgilio Piñera",
						"Onelio Jorge Cardoso",
						"Eliseo Diego",
						"Reinaldo Arenas",
						"Leonardo Padura",
						"Gustavo Adolfo Bécquer",
						"Antonio Machado",
						"Luis Rogelio Nogueras",
					],
					hasOther: true,
					hasNone: true,
					noneText: "Ninguno",
					otherText: "Otro? Cual?",
					colCount: 4,
					hasSelectAll: true,
					selectAllText: "Todos",
				},
			],
			title: {
				default: "¿A qué dedicas tu tiempo libre? ",
				es: "Literatura\n",
			},
			description: {
				default: "Literatura",
				es: "\n\n",
			},
		},
	],
};

export default FreeTimeQuestions;
