# Generated by Django 4.0.1 on 2022-02-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('averagetest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('dontcare', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'SubjectTest',
                'verbose_name_plural': 'SubjectTests',
            },
        ),
    ]
