# Generated by Django 4.0.1 on 2022-02-13 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_alter_question_options_remove_question_sortid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themes',
            options={'verbose_name': 'Theme', 'verbose_name_plural': 'Themes'},
        ),
        migrations.AlterField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.themes'),
        ),
        migrations.AlterField(
            model_name='themes',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.themes'),
        ),
    ]
